version: "3.8"

services:
  web:
    image: my-web-app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - SECRET=${SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - url=${url}
      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET={GOOGLE_SECRET}
